server:
  port: 9092

spring:
  application.name: sboot-apro-simu-atom-modelo-aband
  kafka:
    client-id: sboot-apro-simu-atom-modelo-aband
    producer:
      retries: 3
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        interceptor.classes: br.com.bv.workshop.messaging.KafkaProducerInterceptor
    consumer:
      group-id: group-consumer-sboot-apro-simu-atom-modelo-aband
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific.avro.reader: true
        interceptor.classes: br.com.bv.workshop.messaging.KafkaConsumerInterceptor
    properties:
      bootstrap.servers: pkc-6ojv2.us-west4.gcp.confluent.cloud:9092
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username='KP4LJLJAQMSOG2KO' password='Cgn5vD88dylB6D7NiEvcFTdtg1SJjlVxmPDAr4c6Gwt/YMDjlat7BDk2I+MSHuGQ';
      security.protocol: SASL_SSL
      session.timeout.ms: 45000
      basic.auth.credentials.source: USER_INFO
      basic.auth.user.info: FJDMW63JAI7KPCZW:ng1LwztraQLVRGl1XOiqC1dspLfEbwyvK239w2xCOHh2k7asRFkJgvTfEEfrHF9S
      schema.registry.url: https://psrc-30dr2.us-central1.gcp.confluent.cloud
      auto.register.schemas: false

topic:
  input: negocio-rodas-simulacao-abandonada-veiculo-leve
  output: negocio-rodas-propensao-cliente

management:
  endpoint.info.enabled: true
  endpoints.web.exposure.include: health,metrics,prometheus,loggers

logging:
  level:
    root: INFO
